# Generated by Django 2.0.4 on 2018-11-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email_vertify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('send_time', models.IntegerField()),
                ('vertify_type', models.CharField(max_length=10)),
                ('is_live', models.BooleanField()),
            ],
            options={
                'verbose_name': '邮箱验证',
                'db_table': 'email_vertify',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('recieveId', models.CharField(max_length=6, null=True)),
                ('sendId', models.CharField(max_length=6)),
                ('replyed_messageId', models.CharField(max_length=8, null=True)),
                ('msgStatue', models.BooleanField()),
            ],
            options={
                'verbose_name': '站内消息',
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('msgId', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('msgType', models.CharField(max_length=10)),
                ('msgContent', models.CharField(max_length=200)),
                ('msgTime', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '消息内容',
                'db_table': 'messageText',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='messageText',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='Inform.MessageText'),
        ),
    ]
