# Generated by Django 2.0.4 on 2018-10-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uName', models.CharField(max_length=20)),
                ('uPwd', models.CharField(max_length=40)),
                ('uSex', models.BooleanField()),
                ('uBornDate', models.CharField(max_length=20, null=True)),
                ('uPhone', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('uEmail', models.CharField(max_length=30, null=True)),
                ('uImg', models.ImageField(upload_to='img/user/')),
                ('uTime', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
