# Generated by Django 2.0.4 on 2018-11-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uId', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('uName', models.CharField(max_length=20)),
                ('uPhone', models.CharField(max_length=15)),
                ('uEmail', models.EmailField(max_length=254)),
                ('uSex', models.CharField(max_length=4, null=True)),
                ('uImg', models.ImageField(default='img/user/default_user.png', upload_to='img/user/')),
                ('uTime', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'db_table': 'user',
            },
        ),
    ]
