# Generated by Django 2.0.4 on 2018-11-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uId',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uPhone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
