# Generated by Django 2.0.4 on 2018-11-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20181101_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uId',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uPhone',
            field=models.CharField(max_length=15),
        ),
    ]
