# Generated by Django 2.0.4 on 2018-11-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='email_vertify',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=10)),
                ('send_time', models.CharField(max_length=20)),
                ('vertfiy_type', models.CharField(max_length=10)),
                ('is_live', models.BooleanField()),
            ],
            options={
                'verbose_name': '邮箱验证',
                'db_table': 'email_vertify',
            },
        ),
    ]
