# Generated by Django 2.0.4 on 2018-11-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_email_vertify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_vertify',
            old_name='vertfiy_type',
            new_name='vertify_type',
        ),
        migrations.AlterField(
            model_name='email_vertify',
            name='send_time',
            field=models.CharField(max_length=30),
        ),
    ]
